### ISSUE TITLE
Single click to Mute and Unmute.

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#8] opened 2017-01-25 14:31 UTC
Feature request:  Allow a click on the Speaker icon to Mute and Unmute audio.

**Comment by ron666** [comment] 2017-01-25 14:35
Thanks for reporting this. It should be by default so I'm checking it right now. I'll keep you posted.

**Comment by DeysonOrtiz** [comment] 2017-01-25 14:38
Wow.  You are fast!  Thank you good sir! :)

**Comment by ron666** [comment] 2017-01-25 14:46
Done. Check the fix by downloading the latest version of the package and let me know

**Comment by DeysonOrtiz** [comment] 2017-01-25 14:56
The audio gets muted now. :)  The only thing missing is for the audio level controller to go down as well.  Right now the audio is mute but the level bar stays up.  Thank you :)

**Comment by ron666** [comment] 2017-01-25 14:58
Gotcha. Working on it right now

**Comment by DeysonOrtiz** [comment] 2017-01-25 14:59
Also, it seems that if we click on the speaker icon again the audio does not unMute.
My recommendation is when a person clicks on the speaker to mute it, the speaker gets the little X you have when audio is down as well, to show that it is mute.  Thank you :)

**Comment by ron666** [comment] 2017-01-25 14:59
Interesting. I see the right behavior.
![screen shot 2017-01-25 at 9 58 39 am](https://cloud.githubusercontent.com/assets/910829/22295432/e18bc766-e2e4-11e6-9765-4a77a19a68e7.png)
![screen shot 2017-01-25 at 9 58 44 am](https://cloud.githubusercontent.com/assets/910829/22295433/e36bf0f6-e2e4-11e6-961f-2bc52a8eb087.png)

**Comment by ron666** [comment] 2017-01-25 15:00
Same for video
![screen shot 2017-01-25 at 10 00 12 am](https://cloud.githubusercontent.com/assets/910829/22295485/1e613fe0-e2e5-11e6-8303-985e8773a5af.png)
![screen shot 2017-01-25 at 10 00 19 am](https://cloud.githubusercontent.com/assets/910829/22295486/1e6e8394-e2e5-11e6-8a51-ce0f3b155744.png)

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:03
That is odd.  It does work on yours but not mine.

**Comment by ron666** [comment] 2017-01-25 15:07
What OS and browser are you using so I can check it? Also did you download the latest version of the plugin?

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:09
Let me re-download and test again.  I am on the latest OSX and using Safari and Firefox.

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:11
Just to confirm:  The best place to download is from your live site: http://www.mediaelementjs.com  ?

**Comment by ron666** [comment] 2017-01-25 15:17
From there or GitHub directly doesn't matter

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:19
Here is the link to my testing site.  I have included the top video which is on its own and the thumbnail videos, which I am testing for my video gallery:  https://mmt.staging.wpengine.com/vimeo-embed-test-4/

**Comment by ron666** [comment] 2017-01-25 15:21
This is the first thing I see:
![screen shot 2017-01-25 at 10 20 29 am](https://cloud.githubusercontent.com/assets/910829/22296379/f6f73e66-e2e7-11e6-8a42-19b54ae8b119.png)

**Comment by ron666** [comment] 2017-01-25 15:26
Also, make sure to clear your cache just in case because that had happened to me in the past.

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:35
I do not know what may cause this error.  I wonder if maybe Vimeo's pickiness for Https. since this is a development site.  But I do not think it would cause the volume issue.  I will clear cache now.

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:38
One thing I forgot to point out is that I have to use this script or the videos will not load. This does not match your documentation on your site, though. 

<script type="text/javascript">jQuery(document).ready(function($) {
    $('#mejs-player').mediaelementplayer();
});
</script>

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:47
I wonder if it has anything to do with With Vimeo background off feature we are testing?

**Comment by ron666** [comment] 2017-01-25 15:47
Yesterday I fixed some issues related to jQuery since users in Wordpress and Drupal couldn't use it, and they confirmed it can be used now. Can you try just using this:
```html
<script type="text/javascript">
$(document).ready(function() { 
    $('#mejs-player').mediaelementplayer(); 
}); 
</script>
```
so I can check what other things might be happening, please?

**Comment by ron666** [comment] 2017-01-25 15:48
I see it working now

**Comment by ron666** [comment] 2017-01-25 15:49
Nevermind I thought it was working

**Comment by ron666** [comment] 2017-01-25 15:53
One thing I did notice is that the controls look like blurry for some reason

**Comment by ron666** [comment] 2017-01-25 15:54
I'd also try to use the unminified version of the plugin to give it a try.

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:56
I used the new script linked above. The larger video play, but the small thumbnails do not.  Please note this is a for wordpress site.  P.S.  Speaker mute not working.  I will try the min version now.

**Comment by ron666** [comment] 2017-01-25 15:56
Oh, I figured out what is it: it's because of the parameters of Vimeo related to background. The problem of using that (I found out this later last night) is that the API won't respond to all of the events

**Comment by ron666** [comment] 2017-01-25 15:58
I'm testing one more thing, but I'll keep you posted. That might not be entirely the cause of the issue.

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:58
That is what I had thought,  Darn vimeo!! :)

**Comment by DeysonOrtiz** [comment] 2017-01-25 15:59
It seems the background feature may be limiting.

**Comment by ron666** [comment] 2017-01-25 16:00
Well, go figure out. It's not the `background` parameter: is the `api` parameter. I disabled it and now it works. I'm testing some more but I'll let you know. It should be ready in a couple of minutes

**Comment by DeysonOrtiz** [comment] 2017-01-25 16:01
Thank you :)

**Comment by ron666** [comment] 2017-01-25 16:13
OK I'll strongly advise you not to use `background` until it stops being experimental. Doesn't mean you can't use it, but you will have to write more JS code to stop the autoplay. The reason why volume (and other things) don't work is because `api=1` is for Froogaloop. So not all the arguments in the query string will work. You can download the latest version of the package and it should work now

**Comment by DeysonOrtiz** [comment] 2017-01-25 16:20
That makes sense.  Let me test your new download.  Thank you so much for all your wonderful help. :)

**Comment by DeysonOrtiz** [comment] 2017-01-25 16:29
Just to confirm?  Are we testing the new JS Script now, since the api=1 will not work for the speaker mute?
<script type="text/javascript">
$(document).ready(function() { 
    $('#mejs-player').mediaelementplayer(); 
}); 
</script>

**Comment by ron666** [comment] 2017-01-25 16:34
Yeah API won't work anymore since we are not using froogaloop

**Comment by DeysonOrtiz** [comment] 2017-01-25 16:45
Got it. 
The new script does not work on the video gallery. But it does on the large one on top: http://mmt.staging.wpengine.com/vimeo-embed-test-4/

 I am using the new script within in the loop:  

 '<script type="text/javascript">
$(document).ready(function() { 
    $('#<?php echo ''.$id.''; ?>').mediaelementplayer(); 
}); 
</script>'

This is the loop script that had worked before: 
'<script type="text/javascript">jQuery(document).ready(function($) {
    $('#<?php echo ''.$id.''; ?>').mediaelementplayer();
});
</script>'

**Comment by DeysonOrtiz** [comment] 2017-01-25 16:54
Please hold on.  It seems I may have discovered a conflict on my end.  Thank you. :)

**Comment by DeysonOrtiz** [comment] 2017-01-25 17:02
Ok.  It is working now: https://mmt.staging.wpengine.com/test-mixitup/

Good thing I was working on a different layout to catch this.  Thank you again for all the great work.  The speaker mute works now.  The only thing missing the tap on the video to pause it.  But from what I understand this will not work right now because of the API=0 and Background=1.   Correct?

**Comment by ron666** [comment] 2017-01-25 17:08
correct :) it's a limitation of this approach. Thanks. Closing this issue now

**Comment by DeysonOrtiz** [comment] 2017-01-25 17:16
With this limitation can we pause all the video with a button or another trigger.  I had hoped to pause the videos when we click on the filter controls.  Or all pause/play controls non-functional with Background=1 other than the one in the player controls?    

I would like to know what our limitations are before I begin to design around it. Thank you again for all your great help! :)

**Comment by ron666** [comment] 2017-01-25 17:24
You can still pause it with the play/pause in the control bar; the only one behavior that won't work is when you click on the video to play or pause

**Closed** 2017-01-25 17:44 UTC

**Comment by DeysonOrtiz** [comment] 2017-01-25 17:53
Thank you!  What is the best way to pay back the favor for all the help you have shown us?

**Comment by ron666** [comment] 2017-01-25 18:00
Just star both projects: the plugins and the mediaelement one and tell your peers that do the same. In the end, it's an open source project and I just want to make sure you are using the best. Knowing that we don't have as many bugs as we had in the past it's my satisfaction. If you wanna post something in social media about the plugin or the help you have received or link back to https://github.com/johndyer/mediaelement, etc. Whatever you can help us to gain visibility again it would be awesome man

**Comment by DeysonOrtiz** [comment] 2017-01-25 18:09
I will!  Thank you again for all your hard work.  I will have some new requests in the near future and I look forward to your awesome help!  Thank you again! :)

**Comment by ron666** [comment] 2017-01-25 18:14
You are welcome :)
